### ISSUE TITLE
TypeError: item.date.toISOString is not a function

### ISSUE THREAD

**Issue by borisovg** [almirfilho/metalsmith-feed-atom#1]
Config:

```
    .use(collections({
        posts: {
            pattern: 'posts/*.html',
            sortBy: 'date',
            reverse: true
        },
    }))
    .use(feed({
      collection: 'posts'
    }))
```

Error:

```
TypeError: item.date.toISOString is not a function
    at entrydata (/home/george/repo/node_modules/metalsmith-feed-atom/src/atom.js:45:43)
    at Array.map (<anonymous>)
    at feeddata (/home/george/repo/node_modules/metalsmith-feed-atom/src/atom.js:31:22)
    at build (/home/george/repo/node_modules/metalsmith-feed-atom/src/atom.js:13:30)
    at Ware.<anonymous> (/home/george/repo/node_modules/metalsmith-feed-atom/src/plugin.js:30:18)
    at Ware.<anonymous> (/home/george/repo/node_modules/wrap-fn/index.js:45:19)
    at next (/home/george/repo/node_modules/ware/lib/index.js:85:20)
    at /home/george/repo/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/home/george/repo/node_modules/metalsmith-collections/lib/index.js:130:5)
    at Ware.<anonymous> (/home/george/repo/node_modules/wrap-fn/index.js:45:19)
```

Versions:
```
Node: v16.13.1
metalsmith@2.3.0
metalsmith-collections@0.9.0
metalsmith-feed-atom@1.0.0
```

**Comment by borisovg** [comment]
Looks like compatibility issue with `metalsmith-date-formatter` plug-in.
